### ISSUE TITLE
兄弟，你的说明文档好简陋啊搞了我将近半个小时。

### ISSUE THREAD

**Issue by kelvinblood** [WXiaoming/disqus-proxy#1]
好了，我就吐个槽。等会写篇记录再回来关掉issue。

感谢哈o(^▽^)o。

**Comment by jiananshi** [comment]
∠( ᐛ 」∠)＿

**Comment by kelvinblood** [comment]
出现了不少问题，不太懂python求指教。我配好了nginx 反向代理，也顺利跑了python app.py(用的python Python 2.7.9)，访问 [http://disqus.kelu.org/](http://disqus.kelu.org/) 显示的json是ok的。

然后我访问最近文章的链接： [http://disqus.kelu.org/comments/recent](http://disqus.kelu.org/comments/recent)，显示错误

TypeError: __call__() takes exactly 1 argument (5 given)

你也可以直接访问去看下。

请问是哪里配置出错了么？

我的配置文件也是倒腾了半天，才把app.py跑起来的 
config中的 PUBLIC_KEY SECRET_KEY 对应的是 API key 和secret么？
username是我的id应该没错，from name是什么？我写的setting里的label，对不对？应该怎么写？

![](http://7vigrt.com1.z0.glb.clouddn.com/blog/pic/201705/QQ%E6%88%AA%E5%9B%BE20170508193112.jpg)

![](http://7vigrt.com1.z0.glb.clouddn.com/blog/pic/201705/QQ%E6%88%AA%E5%9B%BE20170508192440.jpg)

**Comment by kelvinblood** [comment]
感觉配置应该是没问题的。。。就是不知道哪里出错了Orz~~~~

吐槽一下，一开始你没有写明python版本，我用了python 3，报错，然后是没有写 # -*- coding: UTF-8 -*-     继续报错。 现在其实fab deploy 部署一直有问题，跟我说xxx没装，装完之后报错 ImportError: No module named utils 和│There was a problem importing our SSH library (see traceback above) ，我都先留着了Orz

**Comment by KeJunMao** [comment]
@kelvinblood  同。。

```
TypeError
TypeError: __call__() takes exactly 1 argument (5 given)
60.223.133.48 - - [31/May/2017 15:22:27] "GET /comments/recent HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/disqus-proxy/app.py", line 109, in get_recentcomments
    limit=10)
```

**Comment by kelvinblood** [comment]
@KeJunMao 一毛一样，我也是这个。

**Comment by jiananshi** [comment]
`pip install git+https://github.com/disqus/disqus-python.git`
